### ISSUE TITLE
二叉树 初心系列 

### ISSUE THREAD

**Issue by xuliker** [xuliker/kde#110]
#### [二叉树：记录与时代并行的技术人](http://www.iqiyi.com/playlist443370402.html)

* 做事情的态度
  * 不断积累热爱
    * 各式各样的工具
      * 简化、自动化、运维优先
    * 用心做事情
      * 解决长远而不是当下的问题
      * 每次都尽量做得超出预期
    * 吾日三省吾身
      * 读了大量代码、不同风格、不同领域
      * code review
      * 理解书中知识
      * 不断写才能得到质的提升
      * 事情做得长久意义才能显现出来
  * 技术是中性的
    * 编程是未来生活的基本组成部分
    * 工业级标准、民用级标准
    * 发挥社会的创造力
  * 挑战自己
    * 一直逼迫自己去非舒适区
    * 总是想着能学到什么东西
    * 有一个目标，然后要有一个期限
    * 资源相对匮乏逼迫自己创新

* 鸟哥（惠新宸）
  * 阴差阳错学了计算机
  * 第一次雅虎中国面试失败
  * **一直逼迫自己去非舒适区**
  * **遇到机会之前就开始下一步思考，然后等着这样的机会出现**
  * 特别好强，做到比别人强
  * 每次梦到自己都在考试却没有准备
* 崔宝秋（小米）
  * 会写很多小程序，**不断积累热爱**
  * 早期电子邮件使用者
  * 硅谷**感受计算机技术的差别**
    * 做的事情自然而然就是前沿
  * 每次都定下一个目标，赶上了潮流
  * **读了大量代码、不同风格、不同领域**
  * **不断写才能得到质的提升**
* 胡宁（360广告）
  * 技术负责人，初中开始参加信息学竞赛
  * 清华计算机系，CMU博士，随后去了谷歌
  * **小事做好，超出预期**
  * 把命运掌握在自己手上
    * 通过技术和产品推动社会革新，改变生活
  * **技术是中性的，坚持底线，知道什么不能做**
  * 不用在意女性身份，坚持技术者身份
  * 坚持才能走下去
* 覃超
  * 人生前半段是竞争，后半段是发现自己
  * 女朋友鼓励我出国，随后去了CMU
  * 谷歌北京，开复提到了FACEBOOK
  * 和facebook同事一起回国创业
  * 计算机精品教程，**免费获得来做出系统化的课程**
  * **有一个目标，然后要有一个期限**
* 陈皓
  * 我要做的事，失败了，那么惨，还不后悔
  * 提供系统架构和稳定性产品
  * 上机操作才能**理解课本知识**
  * 低着头、不敢看面试官
  * **code review + 各式各样的工具**
  * 磨合与技术推销的过程
  * **工业级标准、民用级标准**
  * **简化、自动化、运维优先**
  * **解决长远而不是当下的问题**
  * 技术一定会让更多的人失业
* 于晶纯
  * **面临变化，我总是想着能学到什么东西**
  * 父亲是无线方向的，8086成长环境
  * 北大心理学系，父亲要求到国外去
  * memory model（记忆模型），辅修计算机
  * 报表组 — 预测组
    * 十四天撸出广告预测系统
  * 没有跳槽是因为觉得自己还能学到很多东西
  * 可以从头建立起梦想的技术团队
  * **用心做事情，好结果都是会来的**
* 冯晓焰
  * 做事情，一做就是十几年
  * **不断证明自己，不断挑战自己，才能让项目不断深入**
  * 没有想要改变什么
  * 软件本身、技术本身、管理本身，早期是会有一些弯路
  * 花了很长时间一步步思索怎么会走到现在这样子
  * **吾日三省吾身**
  * sign of life
  * 技术挑战与自信心，比较可靠
  * 开源是去发现business model，使用什么lincense
  * **事情做得长久意义才能显现出来**
  * 确实有些事情做的不对，需要改进
* 吴瀚清
  * 把互联网安全做彻底
  * 压抑人的个性与大学叛逆的放羊
  * 幻影与云计算安全
  * 通过X年的时间成为XX专家
  * **放弃了很多东西才会倍加珍惜现在的目标**
  * 为了做事情才回来
* 许式伟
  * （思考未来）需要由自己的世界观来判断未来的趋势
  * 到底做什么样的事情商业上是成功的
  * 只投了google但是没有去
  * 突然意识到还没有存储的互联网公司
  * **有没有在发挥社会的创造力，人在改变世界**
  * **资源相对匮乏逼迫自己创新**
  * **编程是未来生活的基本组成部分**
* 汪渊（饿了么）
  * 上交毕业一年开口向家里要钱，太失败了
  * 研究计算机、研究编程，**享受编程的掌控感**
  * 业务量突增，感觉力不从心
  * 用户的角度、商业的角度
  * 率先发现了很对的市场
  * **一开始的选择 + 之后的坚持**
  * 一直诚惶诚恐

**Comment by liker12134** [comment]
其实最重要的是你对这件事情到底有没有激情，并且这激情能够支撑你走下去。
