### ISSUE TITLE
中国开源软件事业发展关键人物

### ISSUE THREAD

**Issue by xuliker** [xuliker/kde#114]
* [中国开源软件推进联盟](http://www.copu.org.cn/about)

  * 刘锋 **清华同方** 总工程师
  * 张东 **浪潮**信息有限公司 总裁助理
  * 田日辉 **联想**集团 副总裁
  * 吴庆波 **国防科大软件所**所长兼教育部开源工程中心 主任 **CPU和操作系统**自主可控

  * 李祥凯 普华基础软件股份有限公司技术部 总经理  **操纵系统**产业化
  * 陈伟 一铭软件股份有限公司 总经理 **国产桌面**操作系统
  * 陈渝 清华大学 副教授  操作系统 **Linux标准化**工作组
  * 陈莉君 西安邮电大学 教授 Linux内核**教学改革**
  * 毛德操 **Linux 专家** 

  * 郑忠源 **华为**技术有限公司中央研究院服务器软件 首席架构师 前**中科红旗**
  * 刘峰 北京交通大学网络管理研究中心 主任 **铁路信息化**
  * 刘江 美团技术研究院 院长 前**CSDN**总编
  * 吴峰光 **Intel**亚太研发有限公司 高级工程师
  * 冯晓焰 **Intel**亚太研发有限公司 首席开源科学家
  * 刘明 **天津麒麟**信息技术公司 顾问
  * 张平 北京大学**知识产权**学院 副院长
  * 黄河燕 北京理工大学计算机学院 院长 **海量语言信息处理**与云计算应用工程技术
  * 侯培新 华为技术有限公司 首席开源技术专家 **移动软件**开发部
  * 章文嵩 滴滴出行有限责任公司 高级副总裁 LVS创始人 设计和**架构大型系统**
  * 蔡维德 北京航空航天大学 教授 千人计划学者 **数字社会与区块链**
  * 吴建平 中国工程院 院士 2015年院士增选 现任清华大学计算机科学与技术系主任 国内**互联网**
  * 廖湘科 中国工程院 院士  2015 国防科学技术大学 教授 “天河一号”**超级计算机**项目总指挥
  * 梅宏 中国科学院 院士 2011 中国科学院院士 1963 **青鸟构件**库系统
  * 高文 中国工程院 院士 北京大学教授 人工智能应用和**多媒体技术**
  * 沈昌祥 中国工程院 院士 浙江大学 1995当选 **信息安全**
  * 倪光南 中国工程院 院士 1939 年生 浙江镇海人 中科院计算所研究员 **汉字系统** 国内第一台计算机
  * 陆首群 中国开源软件推进联盟 名誉主席 **企业和政府关系**很微妙

**Comment by liker12134** [comment]
[2013年度中国杰出开源人物](http://www.csdn.net/article/2013-06-28/2816035-open-source-hero-2013)

1.毛德操

毛德操——美籍华人，1980-1989浙大计算机系工作，1991美国马塞诸塞大学计算机硕士，1991-2002在美国摩托罗拉等公司从事产品研发，2002回国在浙大网新任职。

- 1）著有《Linux内核源代码情景分析》、《Windows内核情景分析》等专著。
- 2）领导Linux兼容内核的研发，已开源发布若干版本。
- 3）所领导团队正在研发既**跨操作系统又跨CPU架构的兼容技术**，准备第一步先做到在ARM架构的平板和手机上直接运行Windows应用，然后将此技术推广到国产CPU。

2.蔡飞

蔡飞——2002年加入富士通南大。目前是FNST Linux部门的负责人。

从2003年起组建Linux团队，目前已经成长到100人规模；在蔡飞的带领下，FNST在Linux内核的ftrace，cgroup，btrfs， kvm，rcu，memory hotplug，LXC等领域都做出了巨大的贡献。FNST同时也**培养出了多名Linux内核和其他知名开源项目的维护者**。

3.刘奖

刘奖——2004年至2010年就职于英特尔开源中心，2011年加入华为，现任华为中央软件院欧拉实室架设部长。

依托Linux Foundation**在华为内部大力推广开源文化，两年内培养了一支三十多人的团队参与Linux社区开发**，在Linux内核多个技术领域作出重要贡献，最新3.10内核贡献排名进入前20，发起ktap开源项目并获得大量关注。

4.宫  力

宫力——北京谋智网络技术有限公司董事长兼首席执行官，全球移动设备高级副总裁。

2008参与创办清华企业家协会并担任北京分会的创始主席。长期担任清华大学校友总会理事会理事。宫力博士现任Mozilla全球移动设备高级副总裁，**负责完全开源开放的Firefox OS**移动设备在全球战略。

5.程旭文

程旭文——开源力量创始人，中国开源及基础软件通用技术创新战略联盟技术技术委员会副主任，上海软件行业协会开源专业委员会副主任。

2002年，与伙伴共同创立灰狐开源社区(huihoo.org)，领导和参与开发了国内第一款开源CORBA产品-Orbas、国内**第一款开源J2EE服务器-JFox**，这是国内通过社区化方式进行开源产品协作研发的最早实践 。

2008年，创立开源力量社区；2009年，发起创建息壤开源社区，目标是**建设一个源于中国的类Apache的开源产品社区**，现已有共同发起人40多位，意向捐赠的开源产品5个。2012年12月，创建“开源力量公开课"，目标是让更多的人掌握开源技术，开源力量公开课每周二举行，每次由开源领域的一位大牛主讲，至今已经举办了20期，有超过1300人在现场和超过3000通过在线直播参加了公开课学习。 

6.王  哲

**王哲——Cocos2d-x开源游戏引擎的创始人**。目前国内大约有60%～70%的iOS和Android手机游戏采用Cocos2d-x引擎开发，在全球则大约是25%的市场占有率。Zynga、Microsoft、Intel、ARM、Nokia及BlackBerry的工程师正参与这个开源项目的开发，Microsoft、Intel和Google给予Cocos2d-x开源社区资金赞助。目前，Cocos2d-x的教程书籍已经有5本中文、3本日文、1本韩文、1本英文印刷出版。

7.王文睿

王文睿——2005年中国科学技术大学博士毕业后，加入英特尔公司。

王文睿博士在2011年底创造性的提出了**node-webkit项目**。之后在GitHub上以开源的方式开发。

8.朱照远

朱照远——系统开发工程师，开源爱好者，兴趣方向为**高性能网络服务器**。现在在阿里巴巴集团负责Web平台和CDN开发。

发起**Tengine开源项目——基于Nginx的高性能Web服务器**，项目开发非常活跃，成果已被国内外很多家互联网公司使用；参与阿里巴巴集团开源项目组织和推进活动，协助促进公司内的项目进行开源；积极参与国内外的开源组织和活动。 

9.梁  胜

梁胜——Citrix云平台CTO；在加入Citrix之前，梁胜曾是Cloud.com的创始人兼CEO，参与**创建Apache CloudStack开源云平台软件**。

10.陈  钟

陈钟——1989年博士毕业于北京大学计算机系，留校任教。1995年破格晋升教授。2001-2002年美国UCLA计算机系访问教授，2002年回国担任北京大学软件与微电子学院首任院长，2010年至今担任北大信息学院计算机系主任。**长期兼任开源软件推进联盟副秘书长、中日韩第二工作组中方协调人**。

陈钟教授长期致力于**开源软件的教学和人才培养**，曾担任科技部“十一五”科技支撑计划“国产基础软件应用示范”项目中培训系统子课题负责人，领导和推进教育部高校“国家Linux技术推广与培训中心”建设和运行；在北大软件与微电子学院课程体系中创设了开源软件系列硕士研究生课程与综合实践训练，培养和**形成了一支高水平的开源技术师资队伍**，参与承担了“核高基”专项开源软件相关任务；长期担任中日韩开源软件推进论坛第二工作组中方协调人，领导和协调三国模范课程体系开发、开源训练营、开源软件人力资源开发和互认证工作，得到广发支持和认可。

11.惠新宸

惠新宸——新浪微博架构师兼首席PHP技术顾问，**PHP开发组核心成员**，Zend公司顾问。

对开源的突出贡献：作为PHP开发组核心成员，是PHP-5.4, 5.5的主要开发者，为PHP5.5新增多个特性。同时也是APC、ZendOPcache、Msgpack的维护者。作为开源作者，贡献了Yaf(PHP社区第一个以扩展形式提供的PHP框架，是目前最快的PHP框架以及Yar、Yac、Taint等多个开源项目。

12.程辉

程辉—— **UnitedStack的主要创始人**兼CEO、OpenStack基金会董事，他是中国OpenStack最活跃的布道师和实践者。在此之前，他是新浪OpenStack团队的创始人和技术负责人。2013年2月，他怀抱着用OpenStack去统一和颠覆传统IT基础设施和应用的梦想，在硅谷成立了UnitedStack。 

作为中国OpenStack的最早的实践者和布道师，通过2012年一年时间做了32场关于OpenStack的技术、产品和商业等话题的演讲或分享，程辉让国内很多公司和个人第一次了解到了OpenStack；

曾经带领新浪OpenStack团队积极参与OpenStack社区开发，并且在F版本中总贡献排名第四，并在新成立的公司UnitedStack仍继续贡献开源；成为开放云试验平台StackLab，**让无数用户可以免费体验到真实的OpenStack环境；代表新浪与Intel联合成立中国开源云联盟**，联合中国重要的IT企业共同参与开源云计算项目。

13.余  杰

余杰——博士，**UbuntuKylin项目负责人**，曾获得国际大学生数学建模竞赛一等奖，新加坡国立大学博士联合培养。负责UbuntuKylin开源操作系统项目，从事云端融合的操作系统技术研究，在国内外得到广泛关注，吸引了大量开发者和爱好者，UbuntuKylin发布两个月以来，社区爱好者已超过5000人;并在“天河二号”云平台上进行了UbuntuKylin的适配和优化，近期将部署到“天河二号”的大数据处理平台上。

14.李大维

李大维——90年就加入开源软件社区，是FSF的会员，Apache的贡献者，ObjectWeb的董事，贡献和发起了多项开源软件项目，在2010年在上海创立中国的第一个创客空间《新车间》，推广开源硬件和创客文化，同时也开发了Ardublock是目前在Arduino社区那里面最受欢迎的图形开发环境。这两年开始推广都市农耕和鱼菜共生，将开源的精神带入到农耕中。担任ObjectWeb的监事，**促成中法共同创建OW2开源软件联盟。联合创办中国的第一个创客空间《新车间》，宣传创客精神和开源硬件**。
