### ISSUE TITLE
Work in Intel

### ISSUE THREAD

**Issue by xuliker** [xuliker/kde#115]
- 吴峰光
- 冯晓焰
- 张锐
- 张衍民
- 黄瀛
- 林铭
- 肖光荣	
- 刘远汉
- 陆宝辂
- 陈渝
- 冯博群
- 金垚
- Eddie Dong
- Jike Song
- Figo Zhang
- Hao Wu
- Hans Peter Anvin
- Andi Kleen
- Mauri Whalen
- Mark Gross

***

- [已离职]Patrick Mochel@Prinicpal Engineer at Intel Corporation@Linux Kernel Topics
  - Man With the Plan
  - https://www.linkedin.com/in/patrick-mochel-07a1921/
- [已离职]Jesse Barness@Intel OTC@Kernel-mode video driver for Linux
  - The Network is Storage
  - https://www.linkedin.com/in/jesse-barnes-abbb531/
  - 美国 旧金山 Redhat Intel
- [已离职]李万鹏@社区@Low-latency KVM Hypervisor	
  - https://www.linkedin.com/in/wanpeng-li-50794375/
  - 曾就职于intel IBM 金山
- [已离职]刘奖@Intel@Reconstruct x86 Interrupt Architecture with Hierarchy IRQ Domain
  - 2004年至2010年就职于英特尔开源中心，2011年加入华为，现任华为中央软件院欧拉实室架设部长。
  - 依托Linux Foundation在华为内部大力推广开源文化，两年内培养了一支三十多人的团队参与Linux社区开发，在Linux内核多个技术领域作出重要贡献，最新3.10内核贡献排名进入前20，发起ktap开源项目并获得大量关注。

**Comment by liker12134** [comment]
* 英特尔初印象

  * 创新文化
    * **用户体验**的创新
    * **设备**的创新
    * **云计算**的创新
    * **计算资源**
    * **制造技术**
  * 技术精英与领袖的输入输出地
    * 英特尔企业文化的六大准则以及人才选择和培养模式
      * 以客户为导向
      * 严明的纪律
      * 质量的保证
      * 鼓励冒险
      * 经结果为导向
      * 创造良好的工作环境
  * work-life-balance
    * 没有严格的打卡制度，各个员工也能比较容易地自主跨部门更换职位

* 公司历史

  * 44名**英特尔架构实验室**的员工，2005年，英特尔架构实验室转变为亚太研发有限公司。
  * **发展计算技术，来改变您的生活，让世界更美好**

* 2000名员工，包括90余名博士生、1300余名硕士生和650多名本科生，有5000余名各院校学生曾在这里实习

  * 1:10:2:20 人才比例
  * 培养了2位**资深首席工程师**
  * 7位**英特尔首席工程师**
  * 95%是土生土长未曾留洋进修过的科研技术人员
  * 21个Intel内部的诺贝尔奖IAA（Intel Achievement Award）

* 技术方向

  * **云计算**
  * **数据中心**
  * **物联网**
  * **可穿戴设备**
  * **存储介质**

* 英特尔亚太的定位

  * 植根中国，跟中国的企业合作，**帮助本土企业成长**，让它们逐步成为具备一定国际竞争力的强大个体
  * **系统研发**才是英特尔在中国的架构实验室最好的定位。
  * 世界**一流的开源的软件公司**，有开源技术中心，一共有200多个工程师

* 相关人物：黄波、王文汉、梁兆柱、何京翔

  * https://www.linkedin.com/in/tianfei-zhu-6331631b/
  * https://www.linkedin.com/in/%E6%B4%8B-%E9%9B%AA-45318aa8/

**Comment by liker12134** [comment]
#### the best way I work in intel is to enjoy

  - **以客户为导向。Intel要求所有员工认真倾听客户、供应商和股东的声音，对他们的要求作出积极反映。公司内部员工之间也有客户的概念，相关联的员工相互之间也成为客户支持的关系。**
  - 质量至上。**Intel公司非常强调每个员工的工作质量**，这是公司在客户心中制造质量神话的过程。Intel是技术领先者，这一切都需要高质量，无论是产品质量，还是技术和服务质量。
  - 鼓励尝试冒险。**所以Intel通过评估风险去降低冒险的风险。如果员工在经过冒险，没有达到什么目标，公司比较宽容他的行为。**
  - 良好的工作环境。一个新员工到Intel公司，会觉得Intel是一个非常奇怪的公司，员工在上班时间表现出来的是心中只有公司，没有自己，**每个员工会觉得：我这种行为符合不符合Intel的价值观、规范，能不能够为Intel的进一步拓展带来好处，很少带着个人的性格。”** 
  - 追求创新。通常都是前瞻了五到七年的，甚至还为更远的将来而作部署和研发。我们在遵循“摩尔定律”的同时还在不断地提高半导体产品的性能，并降低它的成本。你不去做，就会有人去做，**你想要处于一个领先的地位，你就要勇于突破和创新”。**
  - 危机感。**我们的竞争对手时时刻刻在追赶我们，我们一定要拉开差距。这也是Intel为什么会如此忙碌的原因，好像我们有做不完的事，因为大家都在不断地超越。**
  - 开放式的沟通。Intel特别鼓励下级能够对上级提出不同的意见。在Intel，**只要你有一个好的想法和一个好的沟通方式**，你便能够让你的管理层听到，而且你会看到最后结果是因为你的建议而发生了不同的变化。
  - 严明的纪律。英文叫做Disagree but commit，即“我不同意，但是我承诺”。**当一个决策确定了，所有团队成员都必须服从。这个执行不光是嘴上说的执行，而是要真的去做，能有结果拿出来。**
  - 强调以结果为导向。现在许多公司也意识到以结果为导向的重要性。“以结果为导向”并不是说只管结果不管过程，过程也要管，**尤其是会影响到结果的重要过程更要管**。

  #### Intel喜欢员工具备的素质和能力：

  ​      第一，主动性。就是遇到事情是不是能够**主动地去多想一步，主动地去学习，主动地与别人沟通**。Intel也很鼓励员工主**动地掌握自己职业生涯的发展规划。公司有很多的资源，就看你能否找到这些资源为你所用。所以Intel很能锻炼人的独立作战能力和主动性。**用英文来说就叫drive，开车式的，你要做一个driver，一个驾驶员。你要自己驾驶和掌握方向，然后找到你要达到目的地的工具和路径。也就是你要自己给自己铺路。

  ​      第二，学习的能力。这就需要员工**有一种自我激励的学习能力**。IT产业天天在不断变化，**Intel也在不断地否定自己旧的技术去创造新的技术**，所以，员工一定要有学习的愿望和学习的能力。这里又涉及到主动性，这种学习没人规定你学，也不会考试，就靠你自己。

  ​      第三，沟通能力。是一种**更多元化的沟通，如何与不同的对象进行不同的沟通，这就涉及到沟通能力的问题。而且沟通一定要体现沟通的价值。有的人的沟通过于在乎自己，不考虑别人。你要看你的信息是否对别人有价值，你可能要在五分钟内把你最想表达的核心意思说出来，让大家一听就立刻对你的想法感兴趣。**

  ​      第四，视野要宽。现在很多企业，都需要**具备国际化视野、具备跨文化素质的人才**。他们既要懂得国际上的趋势、潮流和惯例，**有非常职业化的专业技能，同时还要了解本地的特点、文化和市场**。

  ​      第五，判断能力。什么时候工作，什么时候生活，**你需要作出合理的判断和把握。要做的事情永远比我们能做的事情多，但如何保证你的决定、你的判断在第一时间是对的**，这是一个很大的挑战。

**Comment by liker12134** [comment]
* 为了持续地竞争力
  * 沟通文化
    * 一个**好的想法**和一个**好的沟通**方式
    * 多元化的沟通
      * **国际化视野、多文化视野**
  * **危机文化**
  * **创新文化**
    * 鼓励尝试冒险 + 善于评估风险
      * 勇于突破和创新
      * Intel为什么会如此忙碌的原因，大家都在**不断地超越**
    * **良好的工作环境**
  * 客户文化
    * **质量文化**
    * 相关联的**员工**相互之间也**成为客户支持**的关系
  * 严明的纪律
    * 当一个决策确定了，所有团队成员都必须服从。要真的去做，能有结果拿出来
  * **主动性、学习性、判断能力**
    * 追求**工作质量**
    * 追求**主动学习**
    * 追求**主动沟通**
