### ISSUE TITLE
GoCN每日新闻 2017-12

### ISSUE THREAD

**Issue by xuliker** [xuliker/kde#129]
[GoCN每日新闻](https://gocn.io/topic/每日新闻)

* 2017-12-05
  * 为你的 Go 应用添加 GUI  https://medium.com/@social_57971/how-to-add-a-gui-to-your-golang-app-in-5-easy-steps-c25c99d4d8e0
* 2017-12-04
  * 最小的完美散列函数 https://blog.gopheracademy.com/advent-2017/mphf/
* 2017-12-03
  * 关于一致性协议和分布式锁 http://mp.weixin.qq.com/s/XCPQGPhY3j8SaTXNS8tB0A
  * AWS Lambda开始支持Go https://www.reddit.com/r/golang/comments/7gogdy/aws_lambda_to_fully_support_go/
  * Funtainer: 容器即函数之美 http://dockone.io/article/2924

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-07) 

1. go pprof 采样何时进行   [http://michaelyou.github.io/2017/12/06/go-pprof-%E9%87%87%E6%A0%B7%E4%BD%95%E6%97%B6%E8%BF%9B%E8%A1%8C/](http://mail01.tinyletterapp.com/gocn/gocn-2017-12-07/10210809-michaelyou.github.io/2017/12/06/go-pprof--e9-87-87-e6-a0-b7-e4-bd-95-e6-97-b6-e8-bf-9b-e8-a1-8c/?c=5f2be44c-ae5f-4c74-b0cd-3657a79feb34)
2. gkvdb v1.81 发布，Go 语言嵌入式 K/V 数据库  [https://www.oschina.net/news/91250/gkvdb-1-81-released](http://mail01.tinyletterapp.com/gocn/gocn-2017-12-07/10210813-www.oschina.net/news/91250/gkvdb-1-81-released?c=5f2be44c-ae5f-4c74-b0cd-3657a79feb34)
3. go语言死循环分析 [http://michaelyou.github.io/2017/12/05/go%e8%af%ad%e8%a8%80%e6%ad%bb%e5%be%aa%e7%8e%af%e5%88%86%e6%9e%90%2f](http://mail01.tinyletterapp.com/gocn/gocn-2017-12-07/10210817-michaelyou.github.io/2017/12/05/go-e8-af-ad-e8-a8-80-e6-ad-bb-e5-be-aa-e7-8e-af-e5-88-86-e6-9e-90-2f?c=5f2be44c-ae5f-4c74-b0cd-3657a79feb34)
4. Golang 网络：核心 API 实现剖析（一） [https://zhuanlan.zhihu.com/p/31644462](http://mail01.tinyletterapp.com/gocn/gocn-2017-12-07/10210821-zhuanlan.zhihu.com/p/31644462?c=5f2be44c-ae5f-4c74-b0cd-3657a79feb34)
5. 如何在Go中构建完整测试的Web应用程序 [https://blog.gopheracademy.com/advent-2017/a-tale-of-two-rands/](http://mail01.tinyletterapp.com/gocn/gocn-2017-12-07/10210825-blog.gopheracademy.com/advent-2017/a-tale-of-two-rands/?c=5f2be44c-ae5f-4c74-b0cd-3657a79feb34)

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-08)

1. Go1.10 beta1 https://beta.golang.org/doc/go1.10
2. 人工智能算法和教程汇总 https://github.com/KeKe-Li/tutorial
3. DevOps 标准体系发布及权威 http://www.uml.org.cn/devops/201712061.asp
4. 腾讯阿里的运维实践（附Devops58个开源工具） http://www.sohu.com/a/198439910_100038984
5. 做好架构师，要懂微服务，汇总微服务架构落地的15种框架 http://www.sohu.com/a/201844693_100038984

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-09)

1. 使用Go 机器学习库来进行数据分析 http://colobu.com/2017/12/07/One-Machine-Learning-for-Go/
2. 用make文件来全自动开发go程序 https://blog.gopheracademy.com/advent-2017/make/
3. 如何提高物联网程序操作数据库大批量执行DML性能 https://www.cockroachlabs.com/blog/multi-row-dml/
4. defer使用的5个陷阱 https://blog.learngoprogramming.com/gotchas-of-defer-in-go-1-8d070894cb01
5. upspin项目error处理库封装 https://commandcenter.blogspot.hk/2017/12/error-handling-in-upspin.html

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-10)

1. Golang1.10前瞻 https://zhuanlan.zhihu.com/p/31820378
2. Golang垃圾回收 https://ninokop.github.io/2017/11/09/Go-%e5%9e%83%e5%9c%be%e5%9b%9e%e6%94%b6
3. 从PHP到Go https://medium.com/@ivanjaros/moving-from-php-to-go-6f06989b3e12
4. 从C/C++/Golang谈计算机语言的巨大进步 http://esr.ibiblio.org/?p=7724
5. 使用kubernetes自动部署Golang程序 https://www.reddit.com/r/golang/comments/7iia5g/selfdeploying_go_apps_with_kubernetes/

**Comment by intel-xulike** [comment]
GoCN每日新闻(2017-12-11)
- 基于属性的程序测试 https://blog.gopheracademy.com/advent-2017/property-based-testing/
- Go实现的GraphQL客户端 https://blog.machinebox.io/a-graphql-client-library-for-go-5bffd0455878
- Go语言中面向对象的一些思考 https://katcipis.github.io/blog/object-orientation-go/
- 利用代码生成解决Go没有范型问题 https://www.calhoun.io/using-code-generation-to-survive-without-generics-in-go/
- docker-slim：优化和保护Docker安全的工具 https://github.com/docker-slim/docker-slim

**Comment by xuliker** [comment]
GOCN每日新闻(2017-12-12)

- 基于机器学习的索引 https://arxiv.org/pdf/1712.01208.pdf
- LiteIDE X33.1 发布 http://liteide.org/blog/LiteIDE-X33.1-Released/
- Goland 开发体验 https://medium.com/@andrey_cheptsov/golands-take-on-go-development-7d2611b14b99
- HTTP 链式路由 https://medium.com/@cashalot/how-to-chain-http-handlers-in-go-33c96396b397
- 分布式时序消息队列 https://github.com/celrenheit/sandglass

**Comment by xuliker** [comment]
GOCN每日新闻(2017-12-13)
1. 阿里的容器技术 https://github.com/alibaba/pouch
2. 从php到go再回到php http://blog.breakthru.solutions/re-moving-from-php-to-go-and-back-again/
3. 走近比特币：一个故事看懂区块链原 https://mp.weixin.qq.com/s/hoRLBOGfDOe57dEzdNzMoQ
4. go符号回归库 https://github.com/MaxHalford/koza
5. 代码重用工具  https://github.com/dc0d/goreuse

**Comment by xuliker** [comment]
GOCN每日新闻(2017-12-14)

- 1.在 Kubernetes上运行 Spark https://jimmysong.io/spark-on-k8s/running-on-kubernetes.html

- 2.Go和机器学习 https://www.dotconferences.com/2017/11/francesc-campoy-flores-machine-learning-and-go

- 3.Go通过Consul实现分布式锁 https://distributedbydefault.com/distributed-locks-with-consul-and-golang-c4eccc217dd5

- 4.Go转换Javascript编译器 https://mat.tm/joy/

- 5.随时随地访问您的Kubernetes集群 https://jimmysong.io/posts/kubernetes-anytime-anywhere/

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-15)
1. 单元测试的艺术 https://www.youtube.com/watch?v=EOpj9aZ8KfoGoCN
2. 使用Go语言解析动态JSON格式 http://eagain.net/articles/go-dynamic-json/
3. 微服务模型：Service Mesh http://philcalcado.com/2017/08/03/pattern_service_mesh.html
4. 如何落地TensorFlow on Kubernetes？https://mp.weixin.qq.com/s/huHm09xfStIw76eN3hL8tA
5. 基于Go技术栈的微服务构建 http://www.uml.org.cn/wfw/201712061.asp

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-16)

1. Go IGDB客户端 https://github.com/Henry-Sarabia/igdb

2. GopherChina 2018 即将到来 https://twitter.com/astaxie/status/941672327015628800

3. 深入理解unsafe.Pointer和System calls https://blog.gopheracademy.com/advent-2017/unsafe-pointer-and-system-calls/

4. 谈谈Linux负载均衡 http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html

5. 全球AI创业公司前100强 https://mp.weixin.qq.com/s/-UpwJR54nD__Yw7v1Bb3VA

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-17)

1. 进程管理工具sir https://github.com/foreversmart/sir
2. 基础优化-最不坏的哈希表: http://www.skywind.me/blog/archives/2006
3. 饿了么异地多活技术实现（一）总体介绍: https://zhuanlan.zhihu.com/p/32009822
4. 浅谈分布式存储系统数据分布方法: http://catkang.github.io/2017/12/17/data-placement.html
5. golang汇编入门: https://lrita.github.io/2017/12/12/golang-asm/

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-18)
1. 通过 HTTP 远程查找想要的 zip 文件 https://blog.gopheracademy.com/advent-2017/seekable-http/
2. 超实用加密入门教程 https://cyberspy.io/articles/crypto101/
3. 利用 csv 处理表格数据 https://appliedgo.net/spreadsheet/
4. 如何在单元测试中 mock 当前时间 https://medium.com/@agatan/timejump-a-library-to-manipulate-the-time-for-testing-in-go-9ccfe5b1ac7d
5. 用 Go 编写的恶意流量分析程序 https://github.com/netxfly/xsec-traffic

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-19)

1. 通过解析器来理解 Go  https://medium.com/@francesc/understanding-go-programs-with-go-parser-c4e88a6edb87
2. Go 面向对象编程  https://icyapril.com/go/programming/2017/12/17/object-orientation-in-go.html
3. 使用 Gin 框架创建 API 服务  https://ryanmccue.ca/creating-an-api-with-golang-gin-framework/
4. Unsafe 包以及系统调用的相关讲解  https://blog.gopheracademy.com/advent-2017/unsafe-pointer-and-system-calls/
5. 手把手教你写 K8s 服务 https://blog.gopheracademy.com/advent-2017/kubernetes-ready-service/

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-20)

1. 我与Go语言的这十年 https://mp.weixin.qq.com/s/iU7gaZNgCsU3DHaHa5PZ_Q
2. 解读netpoll.go https://www.youtube.com/watch?v=xwlo3xigknI
3. 系统设计的万能解法：SNAKE原则 https://mp.weixin.qq.com/s/u8NDvKcYv4ztVVRT_HaUJw
4. 通过go/parser来理解Go程序 https://medium.com/%40francesc/funderstanding-go-programs-with-go-parser-c4e88a6edb87
5. Go生成、执行wasm https://blog.gopheracademy.com/advent-2017/go-wasm/

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-21)

1. ServiceMesh时代的选边与站队（附PPT下载） https://mp.weixin.qq.com/s/hHzDa1T_UKPB97ttFRaDCQ

2. Golang一种全节点比特币实现 https://github.com/btcsuite/btcd

3. Golang数据科学简介 https://www.cheatography.com/chewxy/cheat-sheets/data-science-in-go-a/

4. Golang深度学习 http://gopherdata.io/post/deeplearning_in_go_part_1/

5. Golang如何不用容器做依赖注入 https://medium.com/@nvcnvn/how-difficult-for-handle-dependency-injection-in-go-without-the-help-with-container-a3f570a23d62

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-22)

1. 5种Go测试中的高级技巧 https://segment.com/blog/5-advanced-testing-techniques-in-go/
2. 从零开始构建分布式日志系统 http://bravenewgeek.com/building-a-distributed-log-from-scratch-part-1-storage-mechanics/
3. defer使用的5个陷阱（2） https://blog.learngoprogramming.com/5-gotchas-of-defer-in-go-golang-part-ii-cc550f6ad9aa
4. Serverless架构入门手册 https://www.simform.com/serverless-architecture-guide/5. 使用fasthttp时需要注意的两个点 https://studygolang.com/articles/11966

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-23)
1. Mendelics公司用gopdf库替换python生成公司报表  https://blog.gopheracademy.com/advent-2017/building-medical-reports-in-go/
2. 使用osquery-sdk执行SQL查询服务器系统信息 https://blog.gopheracademy.com/advent-2017/osquery-sdk/
3. 远程控制工具Merlin介绍 https://medium.com/@Ne0nd0g/introducing-merlin-645da3c635a
4. TensorFlow框架机器学习入门手册  https://www.toptal.com/machine-learning/tensorflow-machine-learning-tutorial
5. 2017年go语言学习最佳学习书籍&课程介绍 https://reactdom.com/blog/go-books

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-24)

1. 服务端I/O性能大比拼:Node、PHP、Java、Go www.iteye.com/news/32826
2. 美团DDD业务实践 https://mp.weixin.qq.com/s/jMWuMuIvI1cFThC-WQGbHQ
3. Google开发者大会回顾 http://summary.gdd.zbong.cn/universe
4. fireworq:高性能跨语言任务队列系统 https://github.com/fireworq/fireworq
5. Golang配置管理TOML http://www.cnblogs.com/CraryPrimitiveMan/p/7928647.html

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-25)

- [ ] Brigade: 基于事件的K8s脚本引擎 https://github.com/Azure/brigade
- [ ] 使用go trace跟踪程序执行 https://blog.gopheracademy.com/advent-2017/go-execution-tracer/
- [ ] flagr: 动态配置的A/B测试工具 https://github.com/checkr/flagr
- [ ] Go语言反射入门：根据类型创建对象 https://medium.com/kokster/go-reflection-creating-objects-from-types-part-i-primitive-types-6119e3737f5d
- [ ] lgo: 让Jupyter Notebook支持Go语言 https://github.com/yunabe/lgo

**Comment by xuliker** [comment]
GOCN每日新闻(2017-12-26) 
1. Kuberneters 中 Go 的泛型 https://medium.com/@arschles/go-experience-report-generics-in-kubernetes-25da87430301
2. math/rand 全局锁与 goroutine https://www.myhightech.org/2017/12/22/rand-and-goroutines/
3. 记一次 latency 问题排查：谈 Go 的公平调度的缺陷 http://www.zenlife.tk/go-scheduler-pitfall.md
4. 初学 Go 的几个问题 https://zhuanlan.zhihu.com/p/26005856
5. Go 开源图数据库 https://github.com/cayleygraph/cayley

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-27)

- [ ] 使用GO编写的JIT编译器

 https://medium.com/kokster/writing-a-jit-compiler-in-golang-964b61295f

- [ ] DNS解析器，深入浅出Go语言

 http://liehu.tass.com.cn/archives/1052

- [ ] 商用级Service

 Mesh服务的设计之道 https://mp.weixin.qq.com/s/2I_jXUB5RCseA9YRn0P2FA

- [ ] client-go的使用及源码分析

 http://www.huweihuang.com/article/source-analysis/client-go-source-analysis/

- [ ] 缓存穿透、缓存并发、热点缓存之最佳招式

 https://mp.weixin.qq.com/s/62KJ2mSTGoUTPsq0RjU7lg

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-28)

1.Go模板使用 https://blog.gopheracademy.com/advent-2017/using-go-templates/
2.Golang优秀开源项目汇总 https://www.ctolib.com/topics-2762.html
3.Go开发高负载WebSocket https://medium.freecodecamp.org/million-websockets-and-go-cc58418460bb
4.Golang构建工作池 https://geeks.uniplaces.com/building-a-worker-pool-in-golang-1e6c0fdfd78c
5.机器学习概述 https://feisky.xyz/machine-learning/basic/

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-29)

- [ ] 使用Go的实现工作队列 https://geeks.uniplaces.com/building-a-worker-pool-in-golang-1e6c0fdfd78c
- [ ] Reddit.com网站架构演变 https://www.infoq.com/presentations/reddit-architecture-evolution
- [ ] 一款Go语言开发的验证码生成利器 https://github.com/mojocn/base64Captcha
- [ ] 用Go语言实现数学公式计算 http://bionics.it/posts/equation-centric-dataflow-programming-in-go
- [ ] 深度学习算法学习指南 https://github.com/KeKe-Li/tutorial

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-30) 

- [ ] 1. Go语言中的错误处理 http://ethancai.github.io/2017/12/29/Error-Handling-in-Go/
- [ ] 2. 给你的 Golang 程序添加 GUI (Electron) https://studygolang.com/articles/12065
- [ ] 3. 一个调度系统的开发与性能优化 https://zhuanlan.zhihu.com/p/32439765
- [ ] 4. 年终盘点！2017年超有价值的Golang文章 http://colobu.com/2017/12/28/top-golang-articles-of-2017/
- [ ] 5. Golang 套件管理工具 Glide https://cainmaila.github.io/2017/12/27/golang-glide/

**Comment by xuliker** [comment]
GoCN每日新闻(2017-12-31)

- [ ] 1.  分布式系统下的Go channels https://medium.com/@matryer/introducing-vice-go-channels-across-many-machines-bcac1147d7e2
- [ ] 2. Go Socket编程之teleport框架是怎样炼成的   https://www.jianshu.com/p/7120b8378681
- [ ] 3. 时序数据库技术体系－时序数据存储模型设计 http://hbasefly.com/2017/11/19/timeseries-database-2/
- [ ] 4. RocksDB PhysicalCoreID 慢问题排查 https://www.jianshu.com/p/81a2975f9d7a
- [ ] 5. 追求极简：Docker镜像构建演化史 http://tonybai.com/2017/12/21/the-concise-history-of-docker-image-building/

**Comment by xuliker** [comment]
>GoCN新闻是我从今年4月27开始的一个每日整理新闻栏目，因为我有每天看Go最新动态的习惯，所以我想把自己看到的一些好的资料整理分享给大家，到目前为止坚持每天都发，目前为止已经坚持了八个多月了，各位Gopher的反馈都是非常好，但是我几个月前开始创业，所以目前基本上交给了社区的同学，目前我们有如下的人在给大家服务，感谢他们。
