### ISSUE TITLE
Intelligent travel information perform based on location and voice over

### ISSUE THREAD

**Issue by msharathreddy** [xuliker/kde#195]
Hi there,
This is Sharath,

I have a thought and not decide any title for project please help me.
In my project I have to involve GPS tracking for a particular defined persons and also communication over voice
In this module contains radio, bluetooth and GPS/GPRS
Please tell me particular selected board and appropriate software package and more info.
sorry my English

Thanks and Regards
Sharath

**Comment by xuliker** [comment]
@msharathreddy 
Hi buddy，is this your message left by your chat-bot?
and are you trying to develop an Android APP or a travel-specific embedded  device ?

**Comment by msharathreddy** [comment]
Hi there

i want to develop hardware and software related to the project.
I have a confusion for selecting the hardware board for my project.
project includes radio(mobile ad-hoc network),Bluetooth and GPS please share info. regards this project and relevant software package.

**Comment by xuliker** [comment]
@msharathreddy 
I have no idea about hardware board selection for you device as well as relevant software package.
I closed this issue and good luck.
