### ISSUE TITLE
转正答辩指南

### ISSUE THREAD

**Issue by xuliker** [xuliker/kde#41]
作者：天猪(刘勇)
链接：https://www.zhihu.com/question/63442942/answer/209504371
来源：知乎

**Comment by liker12134** [comment]
**转正答辩小结**

- ppt 主要内容需要精心准备

- ppt 讲演思路需要静心准备

- 全面抓住重点／同时也要注意细节

- 数据可视化／注意积累／注意思路清晰

- 注意答辩受众的感受与事务忙碌状态

- 随时保持被打断／随时注意表情细节

- 把握节奏／保持谦逊与自信的平衡
