### ISSUE TITLE
TCP-IP必知必会

### ISSUE THREAD

**Issue by ghost** [xuliker/kde#82]
#### TCP/IP 必知必会

* Transmission Control Protocol/Internet Protocol

  *  数据帧｛IP 包｛TCP 或 UDP 包｛Data｝｝｝
  *  报头 / 起始帧分界符——MAC 头部——IP 头部——TCP 头部——数据——FCS（帧校验序列）

* 链路层（加一个以太网协议头，CRC 编码）： MTU（Maximum Transmission Unit）为 1500

  * 通过 MAC 来唯一标识
  * 封装成帧: 把网络层数据报加头和尾，封装成帧, 帧头中包括**源 MAC 地址和目的 MAC 地址**。
  * 透明传输: **零比特填充、转义字符**。
  * 可靠传输: 在出错率很低的链路上很少用，但是无线链路 WLAN 会保证可靠传输。
  * 差错检测 (CRC): **接收者检测错误, 如果发现差错，丢弃该帧**。

* 网络层（IP）：IP 数据包的最大长度是 64K 字节 (65535)

  * 所有的 TCP，UDP，IMCP，IGMP 的数据都以 IP 数据格式传输

  * IP 协议没有提供一种**数据未传达以后**的处理机制，这被认为是上层协议：TCP 或 UDP 要做的事情

  * 32 位 IP 地址分为网络位和地址位

  * IP 协议头

    * 八位的 TTL 字段。这个字段规定该数据包在穿过多少个路由之后才会被抛弃。某个 IP 数据包每穿过一个路由器，该数据包的 TTL 数值就会减少 1，当该数据包的 TTL 成为零，它就会被自动抛弃

    ```
    IP 头部和 MAC 头部由 IP 模块负责添加。
         IP 头部：IP 用的头部，包含 IP 头部
         MAC 头部：以太网的头部，包含 MAC 地址
    IP 头部格式如下：
              版本号
              头部长度
              服务类型
              总长度：表示 IP 消息的总长度
              ID 号：用于识别包的编号，一般为包的序列号。如果一个包被 IP 分片，则所有的分片都拥有相同的 ID
              标志：该字段有 3 个比特，有效的是前两个比特。分别表示是否允许分片，当前包是否是分片包
              分片偏移量
              生存时间
              协议号：十六进制表示，TCP：06     UDP：11     ICMP：01
              头部校验和
              发送方 IP 地址
              接收方 IP 地址
              可选字段

    MAC 头部的格式如下：
              接收方 MAC 地址（48 比特，5 字节）
              发送方 MAC 地址
              以太类型：使用的协议类型 0000-05DC：IEEE802.3      0800：IP 协议      0806：ARP 协议      86DD：IPV6
    ```

  * ARP：根据 IP 地址获取 MAC 地址的一种协议

    * ARP（地址解析）协议是一种解析协议，本来主机是完全**不知道这个 IP 对应的是哪个主机的哪个接口**，当主机要发送一个 IP 包的时候，会首先**查一下自己的 ARP 高速缓存**
    * 如果查询的 IP－MAC 值对不存在，那么主机就**向网络发送一个 ARP 协议广播包**，这个广播包里面就有待查询的 IP 地址，而直接收到这份广播的包的所有主机都会查询自己的 IP 地址，如果收到广播包的某一个主机发现自己符合条件，那么就**准备好一个包含自己的 MAC 地址的 ARP 包传送给发送 ARP 广播的主机**。
    * 而广播主机拿到 ARP 包后会更新自己的 ARP 缓存（就是存放 IP-MAC 对应表的地方）。发送广播的主机就会**用新的 ARP 缓存数据**准备好数据链路层的的数据包发送工作。
    * RARP 协议的工作与此相反，不做赘述。

  * ICMP 协议

    * IP 协议并不是一个可靠的协议，它不保证数据被送达，那么，自然的，保证数据送达的工作应该由其他的模块来完成。其中一个重要的模块就是 **ICMP(网络控制报文) 协议。ICMP 不是高层协议，而是 IP 层的协议**。
    * 当传送 IP 数据包发生错误。比如主机不可达，路由不可达等等，**ICMP 协议将会把错误信息封包，然后传送回给主机。给主机一个处理错误的机会**，这 也就是为什么说建立在 IP 层以上的协议是可能做到安全的原因。
    * ping
      * ping 是 **ICMP 应用**，是 TCP/IP 协议的一部分。利用 “ping” 命令可以**检查网络是否连通**，可以很好地帮助我们分析和判定网络故障。
      * 它利用 ICMP 协议包来侦测另一个主机是否可达。原理是**用类型码为 0 的 ICMP 发请 求，受到请求的主机则用类型码为 8 的 ICMP 回应**。
    * Traceroute 
      * Traceroute 是用来侦测**主机到目的主机之间所经路由情况**的重要工具，也是最便利的工具。
      * Traceroute 的原理是非常非常的有意思
        * 它收到到目的主机的 IP 后，首先给目的主机发送一个 **TTL=1 的 UDP 数据包**，
        * 而经过的第一个路由器收到这个数据包以后，就自动把 TTL 减 1，
        * 而 TTL 变为 0 以后，路由器就把这个包给抛弃了，
        * 并同时**产生 一个主机不可达的 ICMP 数据报给主机**。
        * 主机收到这个数据报以后**再发一个 TTL=2 的 UDP 数据报**给目的主机，然后刺激第二个路由器给主机发 ICMP 数据 报。
        * **如此往复**直到到达目的主机。这样，traceroute 就拿到了所有的路由器 IP。

* 传输层（TCP 、UDP）

  * TCP：可靠、面向连接、**面向字节流**、传输效率低、全双工、滑动窗口、慢开始、拥塞避免、快重传、快恢复、慢传输速度、对效率要求低、对准确性要求高或者有连接的场景

    * 面向字节流：面向字节流的话，虽然应用程序和 TCP 的交互是一次一个数据块（大小不等），但 TCP 把应用程序看成是**一连串的无结构的字节流**。TCP 有一个缓冲，当应用程序传送的**数据块太长，TCP 就可以把它划分短**一些再传送

    * SMTP（电子邮件）、TELNET、HTTP、HTTPS、FTP、POP3、SSH

      * 当对网络通讯质量有要求的时候，比如：整个数据要准确无误的传递给对方，这往往用于一些要求可靠的应用，比如 HTTP、HTTPS、FTP 等传输文件的协议，POP、SMTP 等邮件传输的协议。

    * TCP 头部由 TCP 模块负责添加，头部格式如下：（最小２０字节）

      ```
      发送方端口号
      接收方端口号
      序号 (发送数据的顺序编号)：发送方告诉接收方该网络包发送的数据相当于所有发送数据的第几个字节。
      ACK 号 (接收数据的顺序编号)
      数据偏移量
      保留
      控制位：
        URG：表示紧急指针字段有效
        ACK：表示接收数据序号字段有效
        PSH：表示通过 flush 操作发送的数据
        RST：强制断开连接，用于异常中断的情况
        SYN：发送方和接受方相互确认序号，表示连接操作
        FIN：表示断开连接
      窗口：接收方告知发送方窗口的大小 (即无需等待确认认可一起发送的数据量)
      校验和
      紧急指针
      可选字段

**Comment by UvpStar** [comment]
* 数据包分片、重组操作

      - （1）发送方：将数据包分为多个 TCP 头部 + 数据包的组合，TCP 头部中存着不同的数据序号；之后**将多个组合交由 IP 模块**，统一添加 IP 头部和 MAC 头部，IP 头部的 ID 号设为统一的。
      - （2）接收方：Ｐ模块具有分片重组的功能，**如果接收到的包是进过分片的，那么ＩＰ模块会将它们还原成原始的包**。分片的包会在ＩＰ头部的标志字段中进行标记，当收到分片的包时，ＩＰ模块会将其暂时存在内部的内存空间中，然后等待ＩＰ头部中具有相同ＩＤ的包全部到达，因为同一个包的所有分片都具有相同的ＩＤ。此外，**ＩＰ头部还有一个分片偏移量的字段，它表示当前分片在整个包中所处的位置**。根据这些信息，在所有的分片全部收到之后，就可以将它们还原成原始的包。

  * UDP：不可靠、无连接、**面向报文**、传输效率高、一对一、一对多、多对一、多对多、传输速度快、对效率要求高、对准确性要求低

    * UDP 包的首部要占用 8 字节，所以这的 MTU 为 1480－8＝1472，Internet 上的标准 MTU 值为 576
    * 面向报文：面向报文的传输方式是**应用层交给 UDP 多长的报文，UDP 就照样发送**，即一次发送一个报文。因此，应用程序必须选择合适大小的报文。**若报文太长，则 IP 层需要分片**，降低效率。若太短，会是 IP 太小。
    * DNS、TFTP（文件传输）、SNMP（网络管理）、NFS（远程文件服务器）、BOOTP、NTP、DHCP、ECHO、SNMP、ARP
      * 当对网络通讯质量要求不高的时候，要求网络通讯速度能尽量的快，这时就可以使用 UDP。
    * DNS（Domain Name System，域名系统），因特网上作为**域名和 IP 地址相互映射**的一个分布式数据库，能够使用户更方便的访问互联网，而不用去记住能够被机器直接读取的 IP 数串。通过主机名，最终得到该主机名对应的 IP 地址的过程叫做域名解析（或主机名解析）。**DNS 协议运行在 UDP 协议之上，使用端口号 53**。

  * TCP连接建立的三次握手（同步连接双方的序列号和确认号并交换 TCP 窗口大小信息）

    * 第一次握手： 建立连接。客户端发送连接请求报文段，将 SYN 位置为 1，Sequence Number 为 x；然后，客户端进入 SYN_SEND 状态，等待服务器的确认；
      * SYN = 1 Seq = X SYN_SEND状态
    * 第二次握手： 服务器收到 SYN 报文段。服务器收到客户端的 SYN 报文段，需要对这个 SYN 报文段进行确认，设置 Acknowledgment Number 为 x+1(Sequence Number+1)；同时，**自己还要发送 SYN 请求信息，将 SYN 位置为 1，Sequence Number 为 y**；服务器端将上述所有信息放到一个报文段（即 SYN+ACK 报文段）中，一并发送给客户端，此时服务器进入 SYN_RECV 状态；
      * SYN = 1 ACK = X+1 Seq = Y SYN_RECV状态
    * 第三次握手： 客户端收到服务器的 SYN+ACK 报文段。然后将 Acknowledgment Number 设置为 y+1，向服务器发送 ACK 报文段，这个报文段发送完毕以后，客户端和服务器端都进入 ESTABLISHED 状态，完成 TCP 三次握手。
      * ACK = Y+1 Seq = Z ESTABLISHED 状态

  * 为什么要三次握手？

    * 为了防止**已失效的连接请求报文段突然又传送到了服务端**，因而产生错误。

      > 具体例子：“已失效的连接请求报文段” 的产生在这样一种情况下：
      >
      > * client 发出的第一个连接请求报文段并没有丢失，而是在某个网络结点长时间的滞留了，以致延误到连接释放以后的某个时间才到达 server。
      > * 本来这是一个早已失效的报文段。但 server 收到此失效的连接请求报文段后，就误认为是 client 再次发出的一个新的连接请求。于是就向 client 发出确认报文段，同意建立连接。
      > * 假设不采用 “三次握手”，那么只要 server 发出确认，新的连接就建立了。
      > * 由于现在 client 并没有发出建立连接的请求，因此不会理睬 server 的确认，也不会向 server 发送数据。
      > * 但 **server 却以为新的运输连接已经建立，并一直等待 client 发来数据**。
      > * 这样，server 的很多资源就白白浪费掉了。采用 “三次握手” 的办法可以防止上述现象发生。
      > * 例如刚才那种情况，**client 不会向 server 的确认发出确认。server 由于收不到确认，就知道 client 并没有要求建立连接**。”

  * TCP 连接终止的四次握手

    * 第一次分手： 主机 1（**可以使客户端，也可以是服务器端**），设置 Sequence Number，向主机 2 发送一个 FIN 报文段；此时，主机 1 进入 FIN_WAIT_1 状态；这表示**主机 1 没有数据要发送给主机 2** 了；
      * Seq = X Fin = 1 Ack = Z
    * 第二次分手： 主机 2 收到了主机 1 发送的 FIN 报文段，向主机 1 回一个 ACK 报文段，Acknowledgment Number 为 Sequence Number 加 1；主机 1 进入 FIN_WAIT_2 状态；主机 2 告诉主机 1，**我 “同意” 你的关闭请求**；
      * ACK = X+1 Seq = Z
    * 第三次分手： 主机 2 向主机 1 发送 FIN 报文段，**请求关闭连接**，同时主机 2 进入 LAST_ACK 状态；
      * Fin = 1 Ack = X Seq = Y
    * 第四次分手： 主机 1 收到主机 2 发送的 FIN 报文段，向主机 2 发送 ACK 报文段，然后主机 1 进入 TIME_WAIT 状态；主机 2 收到主机 1 的 ACK 报文段以后，就关闭连接；此时，**主机 1 等待 2MSL 后依然没有收到回复，则证明 Server 端已正常关闭**，那好，主机 1 也可以关闭连接了。
      * ACK = Y Seq = X

  * 为什么要四次分手？

    * TCP 协议是一种面向连接的、可靠的、基于字节流的运输层通信协议。TCP 是全双工模式，这就意味着，当主机 1 发出 FIN 报文段时，只是表示主机 1 已经没有数据要发送了，主机 1 告诉主机 2，它的数据已经全部发送完毕了；
    * 但是，**这个时候主机 1 还是可以接受来自主机 2 的数据；**当主机 2 返回 ACK 报文段时，表示它已经知道主机 1 没有数据发送了，但是主机 2 还是可以发送数据到主机 1 的；当主机 2 也发送了 FIN 报文段时，这个时候就**表示主机 2 也没有数据要发送了**，就会告诉主机 1，我也没有数据要发送了，之后彼此就会愉快的中断这次 TCP 连接。

  * 为什么要等待 2MSL？

    * MSL：报文段最大生存时间，它是任何报文段**被丢弃前在网络内的最长时间**。原因有二：
      - 保证 TCP 协议的全双工连接能够可靠关闭
        - 第一点：如果主机 1 直接 CLOSED 了，那么由于 IP 协议的不可靠性或者是其它网络原因，导致主机 2 没有收到主机 1 最后回复的 ACK。那么主机 2 就会在超时之后继续发送 FIN，此时由于主机 1 已经 CLOSED 了，就找不到与重发的 FIN 对应的连接。所以，**主机 1 不是直接进入 CLOSED，而是要保持 TIME_WAIT**，当再次收到 FIN 的时候，能够保证对方收到 ACK，最后正确的关闭连接。
      - 保证这次连接的重复数据段从网络中消失
        - 第二点：如果主机 1 直接 CLOSED，然后又再向主机 2 发起一个新连接，**我们不能保证这个新连接与刚关闭的连接的端口号是不同的。也就是说有可能新连接和老连接的端口号是相同的。**一般来说不会发生什么问题，但是还是有特殊情况出现：
        - 假设新连接和已经关闭的老连接端口号是一样的，如果前一次连接的某些数据仍然滞留在网络中，这些延迟数据在建立新连接之后才到达主机 2，由于新连接和老连接的端口号是一样的，TCP 协议就认为那个延迟的数据是属于新连接的，这样就**和真正的新连接的数据包发生混淆**了。
        - 所以 TCP 连接还要在 TIME_WAIT 状态等待 2 倍 MSL，这样可以保证本次连接的所有数据都从网络中消失。

  * TCP 滑动窗口机制

    * 所谓滑动窗口，**就是在发送一个包之后，不等待 ACK 号的返回，直接发送后续的一系列包**。有效利用等待 ACK 号的这段时间。
    * 窗口大小：能够接收的最大数据量。注意接收缓冲区的概念、TCP 头部中的滑动窗口字段的使用（三次握手时传递互相的窗口大小，并且中途还会更新大小）

* 应用层（http、ftp）

* TCP/IP 协议通信的过程其实就对应着数据入栈与出栈的过程。

  * 入栈的过程，数据发送方每层不断地封装首部与尾部，添加一些传输的信息，确保能传输到目的地。
  * 出栈的过程，数据接收方每层不断地拆除首部与尾部，得到最终传输的数据。

* TCP 与 UDP 的区别

  * 基于连接与无连接；
  * 对系统资源的要求（TCP 较多，UDP 少）；
  * UDP 程序结构较简单；
  * 流模式与数据报模式 ；
  * TCP 保证数据正确性，UDP 可能丢包，TCP 保证数据顺序，UDP 不保证。
  * 回答发送数据前是否存在建立连接的过程。
  * ＴＣＰ过确认机制，丢包可以重发，保证数据的正确性；ＵＤＰ不保证正确性，只是单纯的负责发送数据包。 
  * UDP 是面向报文的。发送方的 UDP 对应用程序交下来的报文，在添加首部后就向下交付给 IP 层。既不拆分，也不合并，而是保留这些报文的边界，因此，应用程序需要选择合适的报文大小。
  * UDP 的头部，只有 8 个字节，相对于 TCP 头部的 20 个字节信息包的额外开销很小。

* 网络编程基本概念 SOCKET编程等

* 参考资料

  * http://blog.csdn.net/qq_25827845/article/details/66975129
