### ISSUE TITLE
昨日重现

### ISSUE THREAD

**Issue by xuliker** [xuliker/kde#85]
### 知识点

- C语言输入输出
- C语言语法
- 数组初始化与数组输出
- 表达式
- 二维数组定义
- sizeof(struct)
- pthread_t 多线程处理
- 函数填充
  - 这是一道分治算法题。
- 判断有向图是否存在回路，利用( )方法最佳 
  - 拓扑排序
  - 求最短路径
  - 求关键路径
- 堆排序与二叉树排序
  - 筛选建堆就是从下至上的下滤法建堆，将序列按照顺序组成一棵二叉树，从叶子节点到根节点，依次进行下滤操作；但是很明显，叶子节点不需要下滤，所以就是从第一个非叶子节点开始
  - 堆是一种**完全二叉树**。对于大顶堆而言，其每个节点的值都大于或等于其左右孩子节点的值；对于小顶堆，其每个节点的值都小于或等于其左右孩子节点的值。对序号为i的节点而言，其左右孩子分别为节点序号为2i和2i+1.
  - 一般堆排序的话我们都把A[0]作为一个哨兵，不存储实际数据，此时（父节点=子节点/2），而题目要求是A[0]存放的是根节点，则我们可以用相同的转换（父节点=（子节点-1）/2）。
  - 对于根元素为最小值的二叉堆，删除最小元素的复杂度是o(logn)
  - 判断堆的办法是把序列看成一棵完全二叉树，按层序遍历，若树中的所有非终端节点的值均不大于(或不小于)其左右孩子的节点的值，则该序列为堆。
  - 堆排序的时间复杂度是（O(n log n)），堆排序中建堆过程的时间复杂度是（O(n)）
  - 关于堆排序复杂度分析
    - 堆排序的时间复杂度为O(nlogn)
    - 整个构建堆的时间复杂度为O(n)
    - 堆排序的空间复杂度为O(1)
    - 堆排序是一种不稳定的排序算法
  - 根元素为最小值的二叉堆：
    - 插入节点时间复杂度为O(log n)
    - 删除节点时间复杂度为O(log n)
    - 查询最小元素的复杂度是o(1)
    - 合并两个堆的复杂度是o(lgn)
- 链表、单循环链
- 分类算法稳定么
- 位运算、逆推
- 位运算找规律
- 二叉树结点规律
- 排序算法中是稳定的且时间复杂度最小
  - 稳定的排序算法：冒泡排序、插入排序、归并排序和基数排序
  - 不是稳定的排序算法：选择排序、快速排序、希尔排序、堆排序
  - 直接插入排序是数据越有序越快，最快时间复杂度可达到O(n) .
  - 选择排序无论何时都是O（n^2）
  - 快速排序越有序越慢，它要从后到前遍历找比基准小的，时间复杂度达到O(n)
  - 当初始序列整体或局部有序时，快速排序性能下降，将退化为冒泡排序
  - 基本有序 === 插入排序（快排最慢）
  - 假设你只有100Mb的内存，需要对1Gb的数据进行排序，最合适的算法是归并排序
  - 有 1000 个无序的整数，希望使用最快的方式找出前 50 个最大的，最佳的选择是堆排序
  - 无关 @ 比较次数  === 初始排列 @ 选择排序
  - 无关 @ 移动次数 === 初始排列 @ 基数排序
  - 无关 @ 时间复杂度 === 初始排序 @ 直接选择排序
  - 堆排序 归并排序 @ 时间复杂度 @ 不会超过nlogn
  - 将两个各有N个元素的有序表归并成一个有序表,其最少的比较次数是 N
  - 适合并行处理的排序算法是 @ 基数排序
  - 精俭排序，即一对数字不进行两次和两次以上的比较
    - 插入排序、归并排序
  - 排序趟数与序列的原始状态有关的排序方法@优化的起泡@快速
  - 将5不同的数据进行交换排序，至多需要比较多少次 @10
  - 排序方法中，最坏情况下比较次数最少的是@堆排序
  - 影响外排序的时间因素主要是内存与外设交换信息的总次数
  - 对n个元素的数组进行快速排序，所需要的额外空间为O(logn)
  - 以下哪种排序算法需要开辟额外的存储空间@归并排序

```
基数排序是通过“分配”和“收集”过程来实现排序。
1） 首先根据个位数值（只看个位）来排序：
110 120 911 122 114 007 119
2） 再看十位（只看十位数值大小）来排序：
007 110 911 114 119 120 122 
3） 最后看百位：
007 110 114 119 120 122

桶排序和基数排序均属于分配排序。分配排序的基本思想：排序过程无须比较关键字，而是通过用额外的空间来"分配"和"收集"来实现排序，它们的时间复杂度可达到线性阶：O(n)。简言之就是：用空间换时间，所以性能与基于比较的排序才有数量级的提高！
 
桶排序(Bucket Sort)，也称箱排序
基本思想：设置若干个箱子，依次扫描待排序的记录 array[0]，array[1]，…，array[n - 1]，把关键字等于 k 的记录全都装入到第 k 个箱子里(分配)，然后按序号依次将各非空的箱子里的记录收集起来，从而完成排序。
 
桶排序所需要的额外空间取决于关键字的个数，若 array[0..n - 1] 中关键字的取值范围是 0 到 m - 1 的整数，则必须设置 m 个箱子。因此箱排序要求关键字的类型是有限类型，否则可能要无限个箱子。一般情况下每个箱子中存放多少个关键字相同的记录是无法预料的，故箱子的类型应设计成链表为宜。

在实现上，桶排序一般采用另外的变种。即：把 [0， m) 划分为 m 个大小相同的子区间，每一子区间是一个桶。然后将 n 个记录分配到各个桶中。因为关键字序列是均匀分布在[0，m)上的，所以一般不会有很多个记录落入同一个桶中。由于同一桶中的记录其关键字不尽相同，所以必须采用关键字比较的排序方法(通常用插入排序)对各个桶进行排序，然后依次将各非空桶中的记录收集起来即可。
```

- 交换机工作在OSI七层

  - 交换机第二层数据链路层，路由器第三层网路层

- 各个路由协议衡量路由的好坏标准

  - 路由权：用于选择最佳路由的信息。

    路由算法修改路由表的基本目的是将最好路由信息添加到路由表中，路由的好坏是由**路由算法根据自己获得的路由信息计算**出来的。对于每一条路由，路由算法产生一种权值来表示路由的好坏。通常情况下，这种权值越小，该路径越好。

    **路由权的计算**可能基于路径某单一特性计算，也可能基于路径多种属性进行计算。有几种路径特性经常被用于权值计算，如下：

    1) 带宽 -- 链路的数据容量。例如，通常情况下10M 以太网链路比 64K 出租线路要更好。

    2) 时延 -- 报文从到达目标网络所需要的时间。

    3) 负载 -- 处于活跃状态的网络资源数量。

    4) 可靠性 -- 每条数据链路的出错率。

    5) 跳数 -- 报文到目的地需要经过的网络数。

    6) 开销 -- 一种人为设定的值，通常由网络管理员根据带宽、线路价格或其他一些因素综合得出。

- 冯诺依曼体系结构 Cache

- 多线程与调度

#### 图

* 拓扑排序算法把一个无向图中的顶点排成一个有序序列。

* 拓扑排序将有向图中的顶点以线性方式进行排序。即对于任何连接自顶点u到顶点v的有向边uv，在最后的排序结果中，顶点u总是在顶点v的前面。一个有向图能被拓扑排序的充要条件就是它是一个有向无环图。

  * 1>从有向图中选一个无前驱的顶点输出

    2>将此顶点和以它为起点的弧删除

    3>重复(1),(2)，直到不存在无前驱的顶点

    4>若此时输出的顶点数小于有向图中的顶点个数，这说明有向图中存在回路，否则输出的顶点顺序即为一个拓扑排序序列

* 22个顶点的连通图中边的条数至少为21

  * n个顶点的连通图至少有n-1条边（树）；
  * n个顶点的简单图（完全图）至少有n*(n-1)/2条边。

* 在一个无向图中，所有顶点的度数之和等于图的边数的（2）倍 

* G是一个非连通无向图，共有28条边，则该图至少有 9 个顶点

  * n个顶点 最多拥有 n(n-1)/2条边

* 用DFS遍历一个无环有向图，并在DFS算法退栈返回时打印相应的顶点，则输出的顶点序列是( ) @ 逆拓扑有序

* 有向图中所有顶点的入度之和等于所有顶点的出度之和的 （1） 倍

* 在一个无向图中，所有顶点的度数之和等于所有边数的 （2）倍。

* 设无向图G中有n个顶点，则该无向图的最小生成树上有（n-1）条边

* 在n个结点的无向图中，若该图是连通图,则其边数大于等于n-1，

* 在n个结点的无向图中，若边数大于(n-2)(n-1)/2，则该图必是连通图

* 图的遍历是从给定的源点出发，每一个顶点仅被访问一次

* 图的深度遍历是一个递归过程

* 最小生成树是无向图的连通子图。从不同的结点开始，图的存储方式不同，生成树都不相同。

* 关键路径表示起点到终点的最长路径（可能存在等长的多条路径，只要满足其长度均等于最长路径即可），关键路径由关键活动组成。
  当关键路径上某个活动的时间缩短,则对于需要包含该关键活动的路径A来说路径长度减少，但是若存在不包含该关键活动的关键路径B，对B并没有影响，且此时A已不满足最长路径的要求，不再是关键路径。
  此外，当关键路径上某个活动的时间增加,则对于需要包含该关键活动的路径A来说路径长度增多，其一定是此时起点到终点的最长路径，故整个工程的时间一定增加。

* 生成树是连通图的包含图中的所有顶点的极小连通子图。

* 如果原图不连通，则不可能存在包含原图中所有顶点的连通子图。

* 1.连通图才有生成树，分为深度优先生成树和广度优先生成树 2.非连通图是生成森林

* 判断出一个有向图是否有环（回路）

  * 深度优先遍历
  * 拓扑排序

#### 并发专项

* 避免死锁的一个著名的算法是 @ 银行家算法

* 在分时操作系统中，进程调度采用（）算法  @ 时间片轮转

* 子进程获得父进程的数据空间，堆和栈的复制品

* 线程可以与同进程的其他线程共享数据，但是它拥有自己的栈空间且拥有独立的执行序列

* 线程执行开销小，但是不利于资源管理和保护

* 某系统中有3个并发进程，都需要同类资源4 个，试问该系统不会发生死锁的最少资源数是 10 @ （4-1）*3+1

* 解决并发操作带来的数据不一致性问题，一般采用的方法 @ 封锁

* 时间片调度属于__@并发__，多线程分别绑定CPU属于__@并行__

* ```
  此条件是1966年Bernstein首次提出来，故称为Bernstein条件
  若两个程序P1和P2能满足下述条件，它们便能并发执行，否则不能：
   R(P1)∩W(P2)∪R(P2)∩W(P1)∪W(P1)∩W(P2)={}，
    
  P1的读集与P2写集的交集、P2的读集与P1的写集的交集、P1的写集与P2的写集的交集，三者同时为空集。
  ```

* 多个线程可同时操作一个数据，为了保证该数据的准确性，可将操作该数据的部分改为 @ 同步

* 并发操作会带来哪些数据不一致性？@ 丢失修改、不可重复读、脏读

* 共享内存和使用信号量一样，属于进程间通信的一种方式。

* 尽管每个进程都有自己的内存地址，不同的进程可以同时将同一个内存页面映射到自己的地址空间中，从而达到共享内存的目的

* 线程同步的方法包括使用临界区，互斥量，信号量等

* 两个线程同时对简单类型全局变量进行写操作也需要互斥

* 可重入函数不可以调用不可重入函数

* 计算机操作系统出现死锁的原因是什么

  * 若干进程因竞争资源而无休止的等待着其他进程释放已占有的资源

* 数据库以及线程发生死锁的必要条件是什么

  * 互斥条件：一个资源每次只能被一个进程使用
  * 请求与保持条件：一个进程因请求资源而阻塞时，对已获得的资源保持不放。
  * 不剥夺条件:进程已获得的资源，在末使用完之前，不能强行剥夺。
  * 循环等待条件:若干进程之间形成一种头尾相接的循环等待资源关系。

* 同步机制应该遵循哪些基本准则？

  * 空闲让进
  * 忙则等待
  * 有限等待
  * 让权等待

* 关于多线程，多进程，多任务的区别与关系描述正确的有

  * 线程是指进程内的一条执行线路，或者说是进程中可执行代码的单独单元，它是操作系统的基本调度单元。
  * 一个进程至少有一个线程，即主线程，也可以有多个线程协同工作。
  * 进程从主线程开始执行，进而可以创建一个或多个附加线程来执行该进程内的并发任务，这就是基于线程的多任务。

* 大家要知道 C语言中的 ++ 和 += 并不是原子操作，而是通过多条微程序组成的，因此 ++ 和 += 在执行过程中可能被中断的

  * 第一种可能情况：现在假设两个线程没有并行顺序执行的那么结果显然是 4。

  * 第二种可能情况：再假设现在第一个n++ 已经执行完了  但是结果还没有写回内存 这个时候 n+=2 已经全部执行完 2 写进了内存 结束 然后回到n++的写回操作 这个时候内存就从2被改回1了，后面再来一次n++  结果就为2。

  * 第三种可能情况： 第n+=2 先读取n的值到寄存器 即0入寄存器 这个时候被中断   第一个n++开始执行 并直到结束 内存被改成了1 ，然后 n+=2 继续执行 结束后内存变为2  第二个n++再执行 结果就是3了

  * ```
    编译出来（一般来讲）大概会是这么几步： 
    读a
    +1
    写a
    再读a （这个可能被编译器优化掉）
    写到屏幕上
    ```

* 轮询任务调度与抢占式任务调度的区别

  * 轮询调度优点是其简洁性，它无需记录当前所有连接的状态，所以它是一种无状态调度
  * 抢占式调度实现相对较复杂

* 无锁化编程有哪些常见方法？

  * 针对计数器，可以使用原子加
  * 只有一个生产者和一个消费者，那么就可以做到免锁访问环形缓冲区（Ring Buffer）
  * RCU（Read-Copy-Update），新旧副本切换机制，对于旧副本可以采用延迟释放的做法
  * CAS（Compare-and-Swap），如无锁栈，无锁队列等待

**Comment by liker12134** [comment]
`1．每天中午从法国塞纳河畔的勒阿佛有一艘轮船驶往美国纽约，在同一时刻纽约也有一艘轮船驶往勒阿佛。已知 横渡一次的时间是 7 天 7 夜，轮船匀速航行，在同一航线，轮船近距离可见。
请问今天中午从勒阿佛开出的船会遇到几艘从纽约来的船？

2．巴拿赫病故于1945年8月31日,他出生的年份恰好是他在世某年年龄的平方与他该年龄的差，问：他是哪年出生的？
答案：
设他在世时某年年龄为 x，则 x 的平方<1945，且 x 为自然数。在世时某年年龄为 x的平方-x=x（x-1），他在世年龄 1945-x
（x-1）。 1945 的平方根=44.1，则 x 应为 44 或略小于此的数。而 x=44 时，x（x-1）=44×43=1892，算得其在世 年龄为 1945-1892=53；又 x=43 时，x（x-1）=43×42=1806，得其在世年龄为 1945-1806=139；若 x 再取小，其在 世年龄越大，显然不妥。故 x=44，即他出生于 1892 年，终年 53 岁。

笔试题目

1．设计一个重采样系统，说明如何 anti-alias。
2．y1（n）=x（2n），y2（n）=x（n/2），问：
如果 y1 为周期函数，那么 x 是否为周期函数？
如果 x 为周期函数，那么 y1 是否为周期函数？
如果 y2 为周期函数，那么 x 是否为周期函数？
如果 x 为周期函数，那么 y2 是否为周期函数？

3．如果模拟信号的带宽为 5kHz，要用 8k 的采样率，怎么办。

4．某个程序在一个嵌入式系统（200M 的 CPU，50M 的 SDRAM）中已经最优化了，换到另一个系统（300M 的 CPU，50M 的 SDRAM）中运行，还需要优化吗？

5．x^4+a*x^3+x^2+c*x+d 最少需要做几次乘法。

6．三个 float:a,b,c
问值：
（a+b）+c==（b+a）+c
（a+b）+c==（a+c）+b

7．把一个链表反向填空。

8．下面哪种排序法对 12354 最快？
A.quick sort
B.buble sort
C.merge sort

9．哪种结构平均来讲获取一个值最快？
A.binary tree
B.hash table
C.stack

10．
#include
"stdafx.h"
#include <iostream.h> struct bit
{ int a:3; int b:2; int c:3; };
int main(int argc, char* argv[])
{
bit s;
char *c = (char*)&s; *c = 0x99;
cout <<
s.a <<endl <<s.b<<endl<<s.c<<endl; return 0;
}
Output:?

11．

挑 bug，在 linux 下运行： 
#include <stdio.h>
char *reverse(char* str)
{
int len=0, i=0;
char *pstr=str, *ptemp,*pd; while(*++pstr)
len++; pstr--;
//ptemp=(char*)malloc(len+1);
ptemp=(char*)malloc(len+1);
pd=ptemp; while(len--){ *ptemp=*pstr; ptemp++; pstr--;
i++;
}
*ptemp=*pstr;
ptemp++;
*ptemp='\0'; return pd;
}
main()
{
char string[40]= "Hello World!"; char *pstr=string;
printf("%s", pstr); printf("%s", reverse(pstr));
}`

**Comment by UvpStar** [comment]
- https://www.ibm.com/developerworks/cn/linux/thread/posix_threadapi/part1/index.html
