### ISSUE TITLE
浮点数处理特供（快速入门）

### ISSUE THREAD

**Issue by ghost** [xuliker/kde#86]
#### 软件移植性上的挑战
  * 浮点数标准 IEEE754
    * 标准规定了：  
      * 短浮点数（又称单精度浮点数）float
        * 24 位有效数字，并总共占用 32 位
      * 长浮点数（又称双精度浮点数）long
        * 53 位有效数字精度，并总共占用 64 位
      * 临时浮点数（又称扩展精度浮点数，这种浮点数没有隐含位）
        * 单精度扩展
        * 双精度扩展 long double
          * 必须至少具有 64 位有效数字，并总共占用至少 79 位
          * 实现者可以选择符合该规定的格式，一旦实现，则为固定格式。例如：x86 FPU 是 80 位扩展精度，而 Intel 安腾 FPU 是 82 位扩展精度
    * 单精度浮点数（1-8-23）、双精度浮点数（1-11-52） @ [IEEE754](http://homepages.math.uic.edu/~jan/mcs471/Lec3/ieee754.pdf)
      * （1） 当 P = 0, M = 0 时，表示 0。
      * （2） 当 P = 255, M = 0 时，表示无穷大，用符号位来确定是正无穷大还是负无穷大。
      * （3） 当 P = 255, M != 0 时，表示 NaN（Not a Number，不是一个数）

  * 浮点数表示
    * S 是符号位，P 是阶码，M 是尾数
      * S 是符号位，只有 0 和 1，分别表示正负；
      * P 是阶码，通常使用移码表示（移码和补码只有符号位相反，其余都一样。
        * 对于正数而言，原码，反码和补码都一样；
        * 对于负数而言，补码就是其绝对值的原码全部取反，然后加 1
        * @IEEE754，阶码 P 的最大值是 11111110（因为 255 用于特殊的约定

  * 浮点数精度
    * 浮点数以有限的 32bit 长度来反映无限的实数集合，因此大多数情况下都是一个近似值。同时，对于浮点数的运算还同时伴有**误差扩散**现象。特定精度下看似相等的两个浮点数可能并不相等，因为它们的**最小有效位数**不同。 
    * 由于浮点数可能无法精确近似于十进制数，如果使用十进制数，则使用浮点数的数学或比较运算可能不会产生相同的结果。 
    * 如果涉及浮点数，值可能不往返。值的往返是指，某个运算将原始浮点数转换为另一种格式，而反向运算又将转换后的格式转换回浮点数，且最终浮点数与原始浮点数相等。由于一个或多个最低有效位可能在转换中丢失或更改，往返可能会失败。

  * 浮点数与二进制转换
    * 一串 0 和 1 构成的位序列 (Bit Sequence)，逻辑上用三元组 {S，E，M} 表示一个浮点数 N
      * 浮点数 N 的实际值 n 由下列式子表示：n=(-1)S×m×2e，n>0 时，s=0;n<0 时，s=1
      * E 表示 N 的指数位，位于 S 和 M 之间的若干位。对应值 e 也可正可负。
      * M 表示 N 的尾数位，M 也叫有效数字位（Significant）、系数位（Coefficient），或者是 “小数”。

    * 无小数的浮点数转换成二进制

      * 假设要转换的数据是 45678.0f

      * 在处理这种不带小数的浮点数时，直接将整数部分转化为二进制表示：1011001001101110.0，这时要加上一位默认的 1（这是因为按照浮点数规格化的要求，尾数必须化成 1.M 的格式），那么可以表示成：11011001001101110.0。

      * 然后将小数点向左移，一直移到离最高位只有 1 位，也就是 1.1011001001101110，一共移动了 16 位，我们知道，左移位表示乘法，右移位表示除法。所以原数就等于这样：1.1011001001101110 * ( 216 )。现在尾数和指数都出来了。因为最高位的 1 是根据标准加上去的，只是为了满足规格化的要求，这时候需要把这个 1 去掉。尾数的二进制就变成了：1011001001101110。

      * 最后在尾数的后面补 0，一直到补够 23 位，就是：10110010011011100000000。

      * 再回来看指数，根据前面的定义，P-127=16，那么 P = 143，表示成二进制就是：10001111。

        45678.0f 这个数是正的，所以符号位是 0，那么我们按照前面讲的格式把它拼起来，就是：0 10001111 10110010011011100000000。

      * 这就是 45678.0f 这个数的二进制表示，如果我们要得到 16 进制的表示，非常简单，我们只需要把这个二进制串 4 个一组，转换成 16 进制数就可以了。

    * 含小数的浮点数表示为二进制
      * 将 - 8.5 转换为二进制的步骤如下
        * 步骤一：整数部分为 8，则二进制为 1000；小数部分为 0.5，二进制取值为 1。由于浮点数尾数为 23 位，实际包含的数值为 24 位，所以 8.5 在填 0 补充为 24 位后，表示为1000.10000000000000000000
        * 步骤二：把小数点移到第一个 1 的后面，需要左移 3 位, 加上偏移量 127：127+3=130，转换为二进制是 10000010，所以阶码 E 为 10000010。
        * 步骤三：根据步骤一的结果得到 23 位的尾数位 M 为 00010000000000000000000
        * 步骤四：由于 - 8.5 是负数，所以符号位 S 为 1。
        * 步骤五：将符号位 S、阶码 E 和尾数 M 进行拼接，即可得到 - 8.5 的 IEEE 754 浮点数表示，即十六进制的 C1080000，具体为 1 10000010 00010000000000000000000

    * 将纯小数表示成二进制

      * 对于纯小数转化为二进制来说，必须先进行规格化。例如 0.0456，我们需要把它规格化，变为 1.xxxx * （2n ）的形式，要求得纯小数 X 对应的 n 可用下面的公式：
        n = int( 1 + log 2X )
      * 0.0456 我们可以表示为 1.4592 乘以以 2 为底的 - 5 次方的幂，即 1.4592 * ( 2-5 )。转化为这样形式后，再按照上面处理小数的方法处理，得到二进制表示

        1. 01110101100011100010001
      * 去掉第一个 1，得到尾数 01110101100011100010001
      * 阶码为：-5 + 127 = 122，二进制表示为 0  01111010  01110101100011100010001 最后转换成十六进制 11 C7 3A 3D

  * 将二进制转为浮点数

    * 将 IEEE 754 的 32 位浮点数 40490E56 转换为十进制的步骤如下。
      * 步骤一：将 40490E56 转换为二进制，即 0100 0000 0100 1001 0000 1110 0101 0110
      * 步骤二：由步骤一的二进制得到符号位 S、阶码 E 和尾数 M，它们分别是：符号位 S 为 0；阶码 E 为 100 0000 0，真实阶数为 128-127=1; 尾数 M 为 1001001 0000 1110 0101 0110。因此该数的实际小数为（1.10010010000111001010110）2，即十进制数为 1.5707499980926513671875。
      * 步骤三：根据公式 n=（-1）S×m×2e，计算数值，有
        *  n=1.5707499980926513671875×21=3.141499996185302734375

**Comment by UvpStar** [comment]
#### 数学运算差异与准确度要求
  * 加、减
    * （1）对阶操作：小阶向大阶看齐
    * （2）进行尾数加减运算
    * （3）规格化处理：尾数进行运算的结果必须变成规格化的浮点数，对于双符号位（就是使用 00 表示正数，11 表示负数，01 表示上溢出，10 表示下溢出）的补码尾数来说，就必须是
      001×××…×× 或 110×××…×× 的形式
      若不符合上述形式要进行左规或右规处理。
    * （4）舍入操作：在执行对阶或右规操作时常用 “0” 舍 “1” 入法将右移出去的尾数数值进行舍入，以确保精度。
    * （5）判结果的正确性：即检查阶码是否溢出; 若阶码下溢（移码表示是 00…0），要置结果为机器 0；若阶码上溢（超过了阶码表示的最大值）置溢出标志
  * 乘、除、平方根、余数（必须精确无误）、将浮点格式的数舍入为整数值、在不同浮点格式之间转换、在浮点和整数格式之间转换以、比较（必须精确无误）
  * 在现代 CPU，浮点数运算和整数运算差不多拥有同样的效率。在计算密集型应用（比如射线追踪），这意味这可以忽略整数和浮点数计算的开销差异。这也就是说，你不必要对算数进行整数处理优化。
  * 双精度浮点数运算也不比单精度浮点数运算更慢，尤其是在 64 位机器上。我在同一台机器测试射线追踪算法全部使用 double 比全部使用 floats 运行有时候更快，反过来测试也看到了一样的现象（这里的原文是：I have seen ray tracers run faster using all doubles than all floats on the same machine. I have also seen the reverse）。
#### 五种类型的 IEEE浮点异常与舍入规则
  * 无效运算、被零除、上溢、下溢和不精确
      * 双精度能表达的最大数近似于 1.999999 的 1024 次幂，当计算 2 的 1024 次幂的结果时会溢出，但并不是像整数一样进行了截断处理，而是得到一个特殊值 INF（即 infinite，无穷大）
          * 第一种，各种加减乘除、多次方等数学运算超出了计算机表达的范围，出现溢出。
          * 第二种，除 0 操作导致，即一个非 0 的数除以 0，在整型运算中，除 0 在一些 CPU 中会出现异常，但是浮点数是可以计算的，其结果就是 INF，因此当做除法运算时，一定判断除数是否为0
          * INF 与浮点数运算结果仍为 INF，+INF 大于任何浮点数（-INF 小于任何浮点数），任何浮点数除以INF，结果为 0，除此之外还有更严重的后果
      * 计算机表达 NaN 的方法为，指数为全 1，尾数为非 0
          * 0 除 0，无穷除无穷
          * 0 乘以无穷
          * 正无穷加负无穷
          * 计算结果不是有理数（出现虚数）
          * NaN 与任何浮点数运算结果仍为 NaN
          * NaN 与任何浮点比较结果为假
          * 为了避免出现 NaN，必要时做除零判断，无穷判断，开方 /log 对负数进行判断


  * 四种舍入方向
    * 向最接近的可表示的值；@ 用距离该实数最近的浮点数来近似表示
      * 它与四舍五入只有一点不同，对. 5 的舍入上，采用取偶数的方式。
      * 最近舍入模式：Round(0.5) = **0**; Round(1.5) = 2; Round(2.5) = **2**; 
      * 四舍五入模式：Round(0.5) = **1**; Round(1.5) = 2; Round(2.5) = **3**;
      * 当有两个最接近的可表示的值时首选 “偶数” 值；
        * 机会均等才公平，也就是向上和向下各占一半才合理，在大量计算中，从统计角度来看，高一位分别是偶数和奇数的概率正好是 50% : 50%。至于为什么取偶数而不是奇数，大师 Knuth 有一个例子说明偶数更好，于是一锤定音。
    * 向负无穷大（向下）；
      * 向负无穷大（向下）舍入：C/C++ 函数 floor()。例如：floor(1.324) = 1，floor(-1.324) = -2
    * 向正无穷大（向上）
      * 向正无穷大（向上）舍入：C/C++ 函数 ceil()。ceil(1.324) = 2。Ceil(-1.324) = -1
    * 向 0（截断）
      * C/C++ 的类型转换。(int) 1.324 = 1，(int) -1.324 = -1;
#### 编译器对浮点数的处理
  * 没有–fexpensive-optimizations 时（-O0、-O1）,C++ 语句score += fsv[i] * fw[i] 生成的汇编指令为fadd和fmul，而打开此优化参数时，生成的汇编指令为fmadd
  * 指令*fmadd*（浮点数加乘融合指令）是指令*fadd*和*fmul*的优化，其将浮点数的乘法和加法看成不可分的一个操作，不对中间结果进行舍入，降低了延迟，减小了实现的代价
  * –fexpensive-optimizations 优化参数的优化项里很有可能包含了启用 -ffp-contract。而 -O2、-O3 优化选项启用了–fexpensive-optimizations，使汇编代码生成浮点数操作的融合指令fmadd，而不是fadd和fmul。融合指令fmadd将浮点数的乘法和加法看成不可分的一个操作，不对中间结果进行舍入，从而导致了计算结果有所差别。
  * 当在编译命令中显示添加命令 -std 来指定采用何种 c 标准，gcc 默认采用 gnu89 标准。在这个测试用例中，gnu89 对临时浮点数 (即 2.0/3L) 采用 8 个字节表示，但是 c89 采用 10 个字节表示。显然 10 个字节表示浮点数精度更高，进行浮点运算时结果更加准确。
* 浮点值与体系结构
  * 单个 CPU 可以同时执行 4 个浮点数乘
  * 整数和浮点数指令通常操作不同的寄存器，所以转换需要进行一次拷贝操作。
  * x86 FPU 的默认舍入模式是最近舍入，也就是每次浮点计算结果都采用最近舍入模式，除非用程序显式设置为其它三种舍入模式
  * x86 架构的 CPU 都是 Little Endian 的（也就是低位字节在前，高位字节在后），所以在实际内存中该数字是按上面二进制串的倒序存储的。
#### 浮点数与网络字节序
  * 为什么在网络编程中，需要考虑字节序的问题时，对于 double、float 以及字符串等数据类型不需要考虑主机序列和网络序列之间的转换？
    * float 和 double 与 CPU 无关。一般来说，编译器是按照 IEEE 标准解释的，即把 float/double 看作 4/8 个字符的数组进行解释。因此，只要编译器是支持 IEEE 浮点标准的，就不需要考虑字节顺序。
  * 因此浮点数在网络传输时也要考虑大小端的问题，因为在不同大小端类型的 cpu 上，以上各个位域的顺序也是不一致的。目前对浮点数进行网络传输时网上最普遍的做法是：
    * 把浮点数当作字符串来传送；
    * 双方约定好，把 float 拆分成四个字节按一定顺序进行传输；

**Comment by UvpStar** [comment]
#### 高效代码编写指南
  * 在精度允许的条件下，将浮点数定点化: 浮点指令要比定点指令慢很多，功耗也大很多，在精度要求不那么高的情况下，就可以将浮点数定点化，用定点指令来代替浮点指令

  * 在进行精确计算时 (例如: 货币计算) 避免使用 float 和 double，浮点数计算都是不精确的

  * 在 Win32 下，把 int, 指针地址, long 等 4 字节整数赋给一个 double 后，再用该 double 数赋给原始类型的数，得到的结果于最初的数值一致，即不存在任何精度丢失
    * 对于 long long 或 win64 下的指针地址等 8 字节整数将存在精度丢失

  * 浮点数打印
    * 许多 C/C++ 的库中在输出 double 时，通常有意使得输出结果简短些（即使设置了足够多的可见位数），以避免较大位数的输出。直接使用 C 中的 printf 或 cout 打印 double 数时，打印显示的结果也有可能是带有精度丢失的结果

* 计算机浮点数相关 API（linux）

  ```
  int fpclassify(x);   /* 浮点类型判断，返回值如下 */
  FP_NAN  -  x 是 NaN
  FP_INFINITE  -  x 是正无穷或负无穷
  FP_ZERO  -  x 是 0（包括 ±0）
  FP_SUBNORMAL  -  x 太小不能表示，部分处理器不支持或默认关闭
  FP_NORMAL  -  x 不是上面的情况，即是一个正常的浮点数
  int isfinite(x);   /* x 不是 NaN 或者 INF（±∞），返回 1，否则返回 0 */
  int isnormal(x);  /* 调用 fpclassify(x) 返回 FP_NORMAL 时，返回 1，否则返回 0 */
  int isnan(x);  /* x 是 NaN，返回 1，否则返回 0 */
  int isinf(x);   /* x 是 INF（±∞），返回 1，否则返回 0 */
  ```

#### 浮点数小工具
  * 定点数与半精度浮点数互相转换工具
  * 浮点数与半精度浮点数互相转换工具
  * 自研浮点格式 float16 & float32 与 IEEE 标准浮点数以及 Q 格式定点数 互相转换工具
#### 参考资料
  * [浮点数的表示](http://blog.csdn.net/sunmenggmail/article/details/8087784)
  * <http://en.wikipedia.org/wiki/Double-precision_floating-point_format#cite_note-whyieee-1>
  * 深入理解计算机系统，Randal E. Bryant, 机械工业出版社
  * <http://stackoverflow.com/questions/4738768/printing-double-without-losing-precision>
  * Kahan 教授的《Lecture Notes on IEEE 754》
